name: build

on:
  push:
    branches:
      - main
    paths:
      - 'chromium/manifest.json'
      - 'chromium_mv3/manifest.json'
      - 'firefox/manifest.json'

jobs:
  chromium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get install -y zip jq

      - name: Package Chromium
        shell: bash
        run: |
          VERSION=$(jq -r .version chromium/manifest.json)
          ZIP_NAME="chromium-${VERSION}.zip"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          (cd chromium && zip -r "../$ZIP_NAME" .)

      - name: Upload Chromium ZIP
        uses: actions/upload-artifact@v4
        with:
          name: chromium-${{ env.VERSION }}
          path: chromium-${{ env.VERSION }}.zip

  chromium_mv3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get install -y zip jq

      - name: Package Chromium MV3
        shell: bash
        run: |
          VERSION=$(jq -r .version chromium_mv3/manifest.json)
          ZIP_NAME="chromium_mv3-${VERSION}.zip"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          mkdir -p build_mv3
          cp -r chromium/* build_mv3/
          cp -r chromium_mv3/* build_mv3/
          (cd build_mv3 && zip -r "../$ZIP_NAME" .)
          rm -rf build_mv3

      - name: Upload Chromium MV3 ZIP
        uses: actions/upload-artifact@v4
        with:
          name: chromium_mv3-${{ env.VERSION }}
          path: chromium_mv3-${{ env.VERSION }}.zip

  firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get install -y zip jq

      - name: Package Firefox
        shell: bash
        run: |
          VERSION=$(jq -r .version firefox/manifest.json)
          ZIP_NAME="firefox-${VERSION}.zip"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          mkdir -p build_firefox
          cp -r chromium/* build_firefox/
          cp -r firefox/* build_firefox/
          (cd build_firefox && zip -r "../$ZIP_NAME" .)
          rm -rf build_firefox

      - name: Upload Firefox ZIP
        uses: actions/upload-artifact@v4
        with:
          name: firefox-${{ env.VERSION }}
          path: firefox-${{ env.VERSION }}.zip
