name: build

on:
  push:
    branches:
      - main
    paths:
      - 'chromium/manifest.json'
      - 'chromium_mv3/manifest.json'
      - 'firefox/manifest.json'

jobs:
  chromium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get install -y zip jq

      - name: Package Chromium
        shell: bash
        run: |
          VERSION=$(jq -r .version chromium/manifest.json)
          ZIP_NAME="chromium-${VERSION}.zip"
          rm -f "$ZIP_NAME"
          (cd chromium && zip -r "../$ZIP_NAME" .)

      - name: Upload Chromium ZIP
        uses: actions/upload-artifact@v4
        with:
          name: chromium
          path: chromium-*.zip

  chromium_mv3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get install -y zip jq

      - name: Package Chromium MV3
        shell: bash
        run: |
          VERSION=$(jq -r .version chromium_mv3/manifest.json)
          ZIP_NAME="chromium_mv3-${VERSION}.zip"
          rm -f "$ZIP_NAME"
          (cd chromium && zip -r "../$ZIP_NAME" .)
          (cd chromium_mv3 && zip -ur "../$ZIP_NAME" .)

      - name: Upload Chromium MV3 ZIP
        uses: actions/upload-artifact@v4
        with:
          name: chromium_mv3
          path: chromium_mv3-*.zip

  firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get install -y zip jq

      - name: Package Firefox
        shell: bash
        run: |
          VERSION=$(jq -r .version firefox/manifest.json)
          ZIP_NAME="firefox-${VERSION}.zip"
          rm -f "$ZIP_NAME"
          (cd chromium && zip -r "../$ZIP_NAME" .)
          (cd firefox && zip -ur "../$ZIP_NAME" .)

      - name: Upload Firefox ZIP
        uses: actions/upload-artifact@v4
        with:
          name: firefox
          path: firefox-*.zip
