name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - 'chromium/manifest.json'
      - 'chromium_mv3/manifest.json'
      - 'firefox/manifest.json'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get install -y zip jq

      - name: Extract versions
        id: versions
        run: |
          V_CHROMIUM=$(jq -r .version chromium/manifest.json)
          V_MV3=$(jq -r .version chromium_mv3/manifest.json)
          V_FIREFOX=$(jq -r .version firefox/manifest.json)

          echo "chromium_version=$V_CHROMIUM" >> $GITHUB_OUTPUT
          echo "mv3_version=$V_MV3" >> $GITHUB_OUTPUT
          echo "firefox_version=$V_FIREFOX" >> $GITHUB_OUTPUT

          HIGHEST=$(printf "%s\n%s\n%s" "$V_CHROMIUM" "$V_MV3" "$V_FIREFOX" | sort -V | tail -n 1)
          echo "release_version=$HIGHEST" >> $GITHUB_OUTPUT

      - name: Minify Chromium
        uses: devatherock/minify-js@v3.1.0
        with:
          directory: 'chromium'
          add_suffix: false

      - name: Minify Chromium MV3
        uses: devatherock/minify-js@v3.1.0
        with:
          directory: 'chromium_mv3'
          add_suffix: false

      - name: Minify Firefox
        uses: devatherock/minify-js@v3.1.0
        with:
          directory: 'firefox'
          add_suffix: false

      - name: Package Chromium
        run: |
          ZIP_NAME="chromium-${{ steps.versions.outputs.chromium_version }}.zip"
          (cd chromium && zip -r "../$ZIP_NAME" .)

      - name: Package Chromium MV3
        run: |
          ZIP_NAME="chromium_mv3-${{ steps.versions.outputs.mv3_version }}.zip"
          mkdir -p build_mv3
          cp -r chromium/* build_mv3/
          cp -r chromium_mv3/* build_mv3/
          (cd build_mv3 && zip -r "../$ZIP_NAME" .)
          rm -rf build_mv3

      - name: Package Firefox
        run: |
          ZIP_NAME="firefox-${{ steps.versions.outputs.firefox_version }}.zip"
          mkdir -p build_firefox
          cp -r chromium/* build_firefox/
          cp -r firefox/* build_firefox/
          (cd build_firefox && zip -r "../$ZIP_NAME" .)
          rm -rf build_firefox

      - name: Create GitHub Release
        run: |
          TAG="${{ steps.versions.outputs.release_version }}"
          TITLE="v${TAG}"
          gh release create "$TAG" \
            "chromium-${{ steps.versions.outputs.chromium_version }}.zip" \
            "chromium_mv3-${{ steps.versions.outputs.mv3_version }}.zip" \
            "firefox-${{ steps.versions.outputs.firefox_version }}.zip" \
            --title "$TITLE" \
            --notes "Auto-packaged extensions for version $TITLE"
